name: CI

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        node: ['18']
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: pnpm/action-setup@v2.2.4
      - name: Use Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node }}
      - run: pnpm install
      - run: pnpm run build
      - run: cd website && pnpm install
      - run: cd website && pnpm build
  deploy:
    runs-on: ubuntu-20.04
    needs: [build]
    if: github.ref == 'refs/heads/main'
    env:
      GIT_COMMITTER_NAME: Scaleway Bot
      GIT_COMMITTER_EMAIL: github@scaleway.com
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          fetch-depth: '0'
          persist-credentials: false
      - run: git fetch --tags -f
      - uses: pnpm/action-setup@v2.2.4
      - name: Use Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
